[package]
name = "age100"
version = "0.1.0"
authors = ["James DeVore <jdevore4592@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"